server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://jlsicsu:JLSB250887@mongobufallo.inmdmeu.mongodb.net/paneladev
      #host: localhost
      #port: 27017
      #database: paneladev
      #username: admin
      #password: admin